# Generated by Django 5.1.7 on 2025-04-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('text', models.CharField(max_length=512)),
                ('photo1', models.ImageField(upload_to='projects-photo/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='projects-photo/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='projects-photo/')),
            ],
        ),
    ]
