# Generated by Django 5.1.7 on 2025-04-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_project_company_project_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(max_length=255, unique=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo1',
            field=models.ImageField(upload_to='projects-photo/', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='projects-photo/', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='projects-photo/', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.CharField(max_length=512, verbose_name='Описание'),
        ),
    ]
