# Generated by Django 5.1.8 on 2025-05-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_address_alter_project_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
